### ISSUE TITLE
Infrastruktura | Pobranie danych z odpowiedniej kategorii

### ISSUE THREAD

**Issue by Ania-Em** [CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz#14]
Ref Feature #4 
- [x] Utworzenie jednej klasy 
- [x] Utworzenie 3 metod, każda z metod pobiera za pomocą API https://swapi.dev/ dane z odpowiedniej kategorii
- [x] Pre-processing danych, zwraca tablicę obiektów -> klasa
- [ ] W przypadku nie pobrania danych wyrzucany jest Exception

**Comment by KrolMateusz** [comment]
Daily
1. Napisałem klasę do pobierania rekordów z bazy danych oraz klasę do przetwarzania wstępnego (preprocessing) danych.
2. Planuje napisać testy jednostkowe.
3. Miałem problem z testami jednostkowymi, tzn. pobieranie danych z API. Nie udało mi się stworzyć mockupy dla API.
