### ISSUE TITLE
Logika | Tworzenie bazy pytań do danej gry

### ISSUE THREAD

**Issue by Ania-Em** [CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz#15]
Ref Feature #4 

- [x] Tworzenie listy 10 pytań na podstawie wszystkich pytań z danej kategorii

**Comment by bat098** [comment]
1. Zrobiłem: wybiera 10 pytań z bazy wszystkich pytań z danej kategorii
2. Zostało: dodanie 3 błędnych odpowiedzi do pytania
3. Problemy:  Nie jestem pewny poprawności formatu danych wejścia/wyjścia
