### ISSUE TITLE
UI component | Pojedyncza odpowiedź w wielu stanach

### ISSUE THREAD

**Issue by Ania-Em** [CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz#19]
Ref Feature #5

**Comment by Haivex** [comment]
1. Cały plik AnswerButton.ts i AnswerButton.test.js
2. Refactor i poprawki(obstawiam, że będą)
3. Nie wiem czy do końca zrozumiałem co mam zrobić w zadaniu
