### ISSUE TITLE
UI component | Licznik czasu - gwiazda śmierci

### ISSUE THREAD

**Issue by Ania-Em** [CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz#21]
Ref Feature #5 

- [x] Pobranie obrazka
- [x] Utworzenie funkcji wyświetlającej obrazek
- [ ] Utworzenie funkcji zmieniającej kąt wyświetlanego obrazka 360° - 0°
- [ ] Utworzenie timeouta

**Comment by dudeek** [comment]
1. Nic
2. Nic
3. Aktualnie brak

**Comment by dudeek** [comment]
Daily
1. Zrobiłem: nic
2. Zostało: -
3. Problemy: -
