### ISSUE TITLE
Bug | Losowanie odpowiedzi

### ISSUE THREAD

**Issue by KrolMateusz** [CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz#86]
Kiedy ustawiona jest duża liczba pytań, odpowiedzi często się powtarzają. Zmieniała się nawet tylko jedna odpowiedź, 3 pozostają takie same.

**Comment by KrolMateusz** [comment]
<img width="1093" alt="Zrzut ekranu 2021-01-14 o 13 03 00" src="https://user-images.githubusercontent.com/37661247/104588586-e09e7280-5668-11eb-9dbb-941fd77073e9.png">

**Comment by bat098** [comment]
it's not a bug it's a feature :D
